spring:
  resources:
    cache-period: 

server:
  port: 8080
  compression:
    enabled: false

logging:
  level:
    org.springframework.data.mongodb: INFO
    org.springframework: INFO
    org.apache: INFO
    ch: INFO
